// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi3FVPl2Z4WHzbC23vfW5RojFCCmbpOho',
    appId: '1:37162936657:web:6bc09caabcbb3561b54b70',
    messagingSenderId: '37162936657',
    projectId: 'pastafaria-ef3da',
    authDomain: 'pastafaria-ef3da.firebaseapp.com',
    storageBucket: 'pastafaria-ef3da.firebasestorage.app',
    measurementId: 'G-R5ECNVJKHM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuyCPlMNPIA8bpLa0JNqppbcqv8tyfx74',
    appId: '1:37162936657:android:3976e47935ea8600b54b70',
    messagingSenderId: '37162936657',
    projectId: 'pastafaria-ef3da',
    storageBucket: 'pastafaria-ef3da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrkxZ3kAgeoRWJaSIrobg8IzyjROaMhdo',
    appId: '1:37162936657:ios:9cc4fbd9747394a8b54b70',
    messagingSenderId: '37162936657',
    projectId: 'pastafaria-ef3da',
    storageBucket: 'pastafaria-ef3da.firebasestorage.app',
    iosBundleId: 'com.example.pastafara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrkxZ3kAgeoRWJaSIrobg8IzyjROaMhdo',
    appId: '1:37162936657:ios:9cc4fbd9747394a8b54b70',
    messagingSenderId: '37162936657',
    projectId: 'pastafaria-ef3da',
    storageBucket: 'pastafaria-ef3da.firebasestorage.app',
    iosBundleId: 'com.example.pastafara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi3FVPl2Z4WHzbC23vfW5RojFCCmbpOho',
    appId: '1:37162936657:web:64d1381c31a22a05b54b70',
    messagingSenderId: '37162936657',
    projectId: 'pastafaria-ef3da',
    authDomain: 'pastafaria-ef3da.firebaseapp.com',
    storageBucket: 'pastafaria-ef3da.firebasestorage.app',
    measurementId: 'G-01QPLYP7GH',
  );
}
